from .config import *  # noqa: F401,F403

CLS_MODEL_TYPE = "dtfd"
OUTPUT_DIR = f"{OUTPUT_DIR}_dtfd"
DTFD_NUM_GROUP = 4
DTFD_TOTAL_INSTANCE = 4
DTFD_DISTILL_TYPE = "AFS"
DTFD_NUM_RES_LAYERS = 0
DTFD_ATTN_DIM = 128
DTFD_DROPRATE_TIER1 = 0.0
DTFD_DROPRATE_TIER2 = 0.0
DTFD_LOSS_TIER1_WEIGHT = 1.0
DTFD_LOSS_TIER2_WEIGHT = 1.0
