from .config import *  # noqa: F401,F403

CLS_MODEL_TYPE = "clam"
OUTPUT_DIR = f"{OUTPUT_DIR}_clam"
CLAM_GATE = True
CLAM_ATTN_HIDDEN_DIM = 256
CLAM_DROPOUT = 0.25
CLAM_K_SAMPLE = 8
CLAM_SUBTYPING = False
CLAM_NO_INST_CLUSTER = False
CLAM_INST_LOSS = "ce"
CLAM_BAG_WEIGHT = 0.7
