from .config import *  # noqa: F401,F403

CLS_MODEL_TYPE = "dsmil"
OUTPUT_DIR = f"{OUTPUT_DIR}_dsmil"
DSMIL_NONLINEAR = True
DSMIL_PASSING_V = False
DSMIL_DROPOUT_V = 0.0
DSMIL_Q_DIM = 128
DSMIL_LOSS_BAG_WEIGHT = 0.5
DSMIL_LOSS_MAX_WEIGHT = 0.5
DSMIL_INFER_USE_BAG_LOGITS = True
