from .config import *  # noqa: F401,F403

CLS_MODEL_TYPE = "camil"
OUTPUT_DIR = f"{OUTPUT_DIR}_camil"
CAMIL_AGG_DIM = 512
CAMIL_N_LAYERS = 4
CAMIL_TEMPERATURE = 1.2
CAMIL_DROPOUT = 0.15
CAMIL_GATE = True
CAMIL_ATTENTION_DIM = 256
